# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Monthly Music Hackathon"
email: musichackathon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  At Monthly Music Hackathon NYC, musicians, programmers, artists, scientists, composers, hardware tinkerers, and others spend the last Saturday of each month hacking together projects exploring music. At 8pm we have a concert and presentations of the art, technology, and research developed that day. It's open to everyone. Please come participate or observe.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: musichackathon
github_username: musichackathon
github_repo: mmh_jekyll
facebook_username: musichackathon
email_list_signup_url: "http://monthlymusichackathon.us5.list-manage1.com/subscribe?u=498e6061a6f7a0ca8bf5da9f8&id=30b00385af"
eventbrite_url: "https://www.eventbrite.com/o/monthly-music-hackathon-nyc-2470452960"
timezone: America/New_York
date_format: "%b %-d, %Y"
short_date_format: "%b %-d"
time_format: "%I:%M %P"
future: true

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "collection/post"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "collection/event"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "collection/project"
  - scope:
      path: ""
      type: "resources"
    values:
      layout: "collection/resource"

collections:
  events:
    output: true
    permalink: /:collection/:year-:month-:day/
  posts:
    output: true
    permalink: /blog/:year-:month-:day-:title/
  projects:
    output: true
    permalink: /:collection/:year-:month-:day-:title/
  resources:
    output: true
    permalink: /:collection/:name/
